# Generated by Django 4.1.3 on 2023-12-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('CId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=10, unique=True)),
                ('RegionId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityNname', models.CharField(max_length=100)),
                ('PINCode', models.IntegerField(null=True)),
                ('CId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
            ],
        ),
    ]
